service:
  api_listen_address: 127.0.0.1:7701
  kubernetes_api_listen_address: 127.0.0.1:7702
load_balancer:
  kind: f5
  f5:
    iControl_REST_base_URL: http://127.0.0.1:8050
    username: test
    password: test
etcd:
  hostname: 127.0.0.1
  port: 4001
  basepath: /lbaas
